feat: set curl for auto clean up stale assets

diff --git a/stable/meteor/templates/cronjob.yaml b/stable/meteor/templates/cronjob.yaml
--- a/stable/meteor/templates/cronjob.yaml
+++ b/stable/meteor/templates/cronjob.yaml
@@ -33,6 +33,21 @@ spec:
               - -c
               - |
                 meteor run /opt/recipes;
+                METEOR_EXIT_CODE=$?
+                echo "Meteor command exited with code METEOR_EXIT_CODE"
+
+                if [ $METEOR_EXIT_CODE -eq 0 ]; then
+                  {{- if .Values.cleanupStaleAssets.enabled }}
+                    curl -X POST {{ .Values.cleanupStaleAssets.endpoint }} \
+                    -H "Content-Type: application/json" \
+                    {{- range $key, $value := .Values.cleanupStaleAssets.headers }}
+                      -H "{{ $key }}: {{ $value }}" \
+                    {{- end }}
+                    -d '{{- toJson .Values.cleanupStaleAssets.payload }}'
+                   {{- end }}
+                else
+                  echo "Meteor run failed with exit code $EXIT_CODE, skipping delete stale assets request"
+                fi
             {{- if .Values.telegraf.enabled }}
                 pkill -SIGTERM telegraf
             {{- end }}
